{
  "formatVersion": "1.1",
  "component": {
    "group": "io.carrotquest",
    "module": "image-picker",
    "version": "1.0.9-usRelease",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "hr3bubxjmjebplvfnov5j43riq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.14"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "image-picker-1.0.9-usRelease.aar",
          "url": "image-picker-1.0.9-usRelease.aar",
          "size": 308138,
          "sha512": "7d2b2e1d2b22f0a62d236d6d9bf8056a28286999a294f2bf9d698990a188ae2343122758e4fcf2da03355ea9890eb2deefcb1d8eefd1c5cb18dfc9f1aa97259e",
          "sha256": "7b826696a82cbc37edd65edfd2238feaa177cee3010ae254dcc9a18b75839426",
          "sha1": "aa460136ef8d84918c607609c54a43f77f14336b",
          "md5": "59b47f9eefe9036658de9f3ccd82f70f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "image-picker-1.0.9-usRelease.aar",
          "url": "image-picker-1.0.9-usRelease.aar",
          "size": 308138,
          "sha512": "7d2b2e1d2b22f0a62d236d6d9bf8056a28286999a294f2bf9d698990a188ae2343122758e4fcf2da03355ea9890eb2deefcb1d8eefd1c5cb18dfc9f1aa97259e",
          "sha256": "7b826696a82cbc37edd65edfd2238feaa177cee3010ae254dcc9a18b75839426",
          "sha1": "aa460136ef8d84918c607609c54a43f77f14336b",
          "md5": "59b47f9eefe9036658de9f3ccd82f70f"
        }
      ]
    }
  ]
}
